# Generated by Django 4.1 on 2023-03-14 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Famille',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('famille_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Materiel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('marque', models.CharField(max_length=100)),
                ('date_acquisition', models.DateField()),
                ('state', models.CharField(max_length=100)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DMM.fournisseur')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceAffectation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('service', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Reparation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_reparation', models.DateField()),
                ('note', models.CharField(max_length=100)),
                ('materiel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DMM.materiel')),
                ('reparateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DMM.fournisseur')),
            ],
        ),
        migrations.CreateModel(
            name='Reforme',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_reforme', models.DateField()),
                ('note', models.CharField(max_length=100)),
                ('materiel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DMM.materiel')),
            ],
        ),
        migrations.CreateModel(
            name='MaterielType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('designation', models.CharField(max_length=100)),
                ('famille', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DMM.famille')),
            ],
        ),
        migrations.AddField(
            model_name='materiel',
            name='materiel_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DMM.materieltype'),
        ),
        migrations.AddField(
            model_name='materiel',
            name='service_affectation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DMM.serviceaffectation'),
        ),
        migrations.CreateModel(
            name='EnPanne',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_panne', models.DateField()),
                ('note', models.CharField(max_length=100)),
                ('materiel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DMM.materiel')),
            ],
        ),
        migrations.CreateModel(
            name='Affectation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_affectation', models.DateField()),
                ('note', models.CharField(max_length=100)),
                ('materiel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DMM.materiel')),
                ('service_aff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DMM.serviceaffectation')),
            ],
        ),
    ]
